### ISSUE TITLE
cannot decrypt file after encryption using personal RSA keys

### ISSUE THREAD

**Issue by illegalprime** [slok/agebox#181]
I have a key pair that I use for everything, I wanted to test this out with it but I it will not decrypt:
```
$ agebox validate
INFO[0000] Using 1 tracked files                         version=0.6.1
WARN[0000] Could not load private key: invalid private key  key=/home/michael/.ssh/michael_rsa svc=storage.fs.KeyRepository version=0.6.1
WARN[0000] Could not load private key: invalid private key  key=/home/michael/.ssh/michael_rsa.pub svc=storage.fs.KeyRepository version=0.6.1
INFO[0000] Loaded private keys                           keys=2 svc=storage.fs.KeyRepository version=0.6.1
ERRO[0000] Invalid secret: could not decrypt secret: age could not decrypt the secret: no identity matched any of the recipients  secret-id=nixops/secrets/localstate.nixops svc=box.validate.Service version=0.6.1
```

yes, this key has a password on it, but it doesn't work with the `--passphrase` flag either.
I've used this key for so many things, I must be doing something wrong here.

Thanks!

**Comment by wezm** [comment]
I ran into this too. The issue seems to be legacy SSH RSA keys with the header `-----BEGIN RSA PRIVATE KEY-----`. If you regenerate your key with: `ssh-keygen -p -f <path/to/your/private.key>` it will be written out in the new format, which begins with `-----BEGIN OPENSSH PRIVATE KEY-----`.

`-p` requests changing the passphrase for the key specified by `-f`. You can use the same passphrase for old and new.

**Comment by slok** [comment]
Thanks @wezm for the response with the solution, closing!
