### ISSUE TITLE
[ENHANCEMENT] Management of .gitignore in case of present git repository

### ISSUE THREAD

**Issue by thenoseman** [slok/agebox#64]
Hi.
I think it would be a great addition if agebox could manage the adding/removing of the unencrypted filenames not only in `.agebox.yml` but also in the `.gitignore` file.

This is the only feature I am missing from blackbox ATM.

I know that this is strictly speaking not the job of agebox but I would really really like to remove blackbox from my system ;)

Again thank you for being so responsive.

**Comment by slok** [comment]
Hey @thenoseman!

I understand that this is something useful, however, one of the main motivations was to decouple the VCS system from the tool, opposite of tools like BlackBox does, and makes it complex and full of corner cases.

For example, you can use Agebox with Git, a directory on your computer, mercurial, bazaar...

That's why I added the `validate` command, users can use this as a githook, CI check step, along with their regular `make check` actions...

Manipulating a git-specific file is out of the scope of Agebox, however, I would like to propose a possible solution and know your opinion :)

I was thinking of adding a new command called `list`(`ls`) that would list the tracked files, it would have a `--format` flag and this would return the tracked files and their state in the specific format, one format could be `gitignore` and the user would be responsible for taking this data and saving in the `gitignore`. If the user's `gitignore` file is clean and has the final block of files reserved for agebox, this would be simple enough: remove the latest block and do something similar to `agebox list --format=gitignore >> ./.gitignore`

I think that this solution is a midterm between both sides (decoupling the VCS and helper tool for the user).

What do you think? Would this solve your problems and make you an Agebox user? :innocent:

**Comment by thenoseman** [comment]
Hey,
I can understand that managing those files can be a slippery slope. The next person is going to ask vor `.cvsignore` 🤣 
Anyway the whole point is to not allow unencrypted secrets to be published in the VCS of choice.

This of cause can be done simply by running `validate` as a `pre-receive` hook on the VCS server.

I really don't trust anyone (myself included) to install a client side pre-commit hook so server side validation is the best way to go IMHO.

I think the `ls` command should come in handy when parsing the `.yml` file into a script usable format.

For now a `pre-receive` hook is my way forward I think. Won't keep me away agebox anyway 😄
